### ISSUE TITLE
Documentation on how to build the book ?

### ISSUE THREAD

**Issue by revskill10** [isovector/thinking-with-types#1]

**Comment by isovector** [comment]
Yup! There's a makefile and all of the tools are FOSS :)

**Comment by JanPokorny** [comment]
@isovector I'm surprised by your use of "just run xelatex many times" in the Makefile. I thought that latexmk is the common solution for this kind of problem?

**Comment by isovector** [comment]
¯\_(ツ)_/¯ i only know about types

**Comment by JanPokorny** [comment]
Typical.
