### ISSUE TITLE
Your sample chapter is the whole book!

### ISSUE THREAD

**Issue by MarcelloDuarte** [isovector/thinking-with-types#4]
Hi Sandy,

Just passing by to let you know there is a problem with the way your sample chapter is set on leanpub. People downloading the free sample will get the whole book. You should fix it so people will only download a single chapter — unless this is done this way by design, in which case, ignore me :)

**Comment by isovector** [comment]
Thanks for the report! 

I can't reproduce this --- the sample pdf I get off leanpub is 59 pages with md5 `784883731a6f17940b81b4f4eb0ebc40`. Can you share the link you clicked on, and if possible, the md5sum you see on your end?

Cheers!

**Comment by MarcelloDuarte** [comment]
My mistake probably. I just thought that because the sample span many chapters it was the whole book in it, but I am guessing the chapters are all summarised.

**Comment by isovector** [comment]
It's just great value ;) Thanks for reading, and happy new year!
