### ISSUE TITLE
EPUB formatting on leanpub

### ISSUE THREAD

**Issue by mcmayer** [isovector/thinking-with-types#5]
Can you have a look at the formatting of the epub on leanpub? The math images (Latex, I guess) are completely out of proportion. The 1234 blobs that enumerate code lines are a good idea, but they don't work at all in the epub because of their large size.
IMHO the epub is unreadable. Pleeeez fix!

<img width="731" alt="formatting of epub" src="https://user-images.githubusercontent.com/240849/50634107-db709e00-0f4d-11e9-86e0-1d2761b79ed0.png">

**Comment by isovector** [comment]
This is a surprisingly hard problem---the widely supported versions of epub *do not* support math rendering, and so books need to cheat and render them as images. Unfortunately, even this is less straightforward than it should be; different readers have different ideas of what a reasonable font size is, compared with rasterized images.

I don't know of any solution to this; settings that look fine on one ereader will not look good on another. The epub looks OK on my kindle---it's not beautiful, but you'd be hard pressed to call it unreadable. 

As it stands, [the epub generation is horrific enough](https://github.com/isovector/thinking-with-types/blob/master/build-epub.sh#L46-L62) and I am not keen to futz with it any further. I'm going to close this as `wontfix`, but am more than happy to accept pull requests that improve the situation.

The good news is that most of the math peters out after the first three chapters, so if you can push past the big sizes, everything should be fine after that.

**Comment by isovector** [comment]
OK, you're right; that is pretty horrific. Let me try some things.

**Comment by isovector** [comment]
I think I've fixed this---the new build uses unicode points for these symbols rather than images. Trying grabbing the updated epub on leanpub and let me know!
