### ISSUE TITLE
No chapter 2 in sample chapters

### ISSUE THREAD

**Issue by retnuh** [isovector/thinking-with-types#7]
Hi there, I downloaded the [samples](http://samples.leanpub.com/thinking-with-types-sample.pdf) today and have started reading it - it's interesting so far!

However I was confused when I went from Chapter 1 to Chapter 3.  I checked the ToC and sure enough it also goes from 1 to 3.  I was wondering if Chapter 2 is elided from the samples on purpose, or if it's a bug, or an easter egg, or...?

Also, I couldn't find a ToC on the website or LuLu to try to work out which of the above was the issue.

Thanks again, hope it goes well!

**Comment by isovector** [comment]
Chapter 2 is indeed intentionally elided from the sample. I don't remember why I decided that, but I guess it's good to leave 'em wanting more :) Thanks for reading!
